EpisodeDownloader:
    DownloadPath: Downloads
    SavePath: Downloads
    Overwrite: false
    SaveShowsInFolders: true
    SaveSeasonsInFolders: true
    DownloadExtension: mkv
    WatchUrls: []
Logging:
    LogLevel:
        Default: Information
VrtEpisodeProvider:
    Email:
    Password:
VierEpisodeProvider:
    Email:
    Password:
