EpisodeDownloader:
    DownloadPath: Downloads
    SavePath: Downloads
    SaveShowsInFolders: true
    SaveSeasonsInFolders: true
    WatchUrls: []
Logging:
    LogLevel:
        Default: Information
VrtDownloader:
    Email:
    Password:
VierDownloader:
    LastAuthUser:
    RefreshToken:
